// <auto-generated />
using System;
using Clinica.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Clinica.Migrations
{
    [DbContext(typeof(ClinicaDB))]
    [Migration("20230314214443_first")]
    partial class first
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Clinica.Domains.Consulta", b =>
                {
                    b.Property<Guid>("ConsultaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Costo")
                        .HasColumnType("integer");

                    b.Property<int>("CostoMateriales")
                        .HasColumnType("integer");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MedicoId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PacienteH_Clinica")
                        .HasColumnType("uuid");

                    b.HasKey("ConsultaId");

                    b.HasIndex("PacienteH_Clinica");

                    b.ToTable("Consultas");
                });

            modelBuilder.Entity("Clinica.Domains.Doctor", b =>
                {
                    b.Property<Guid>("NMatricula")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Especialidad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("NMatricula");

                    b.ToTable("Doctores");
                });

            modelBuilder.Entity("Clinica.Domains.Paciente", b =>
                {
                    b.Property<Guid>("H_Clinica")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("H_Clinica");

                    b.ToTable("Pacientes");
                });

            modelBuilder.Entity("Clinica.Domains.Consulta", b =>
                {
                    b.HasOne("Clinica.Domains.Paciente", null)
                        .WithMany("Consultas")
                        .HasForeignKey("PacienteH_Clinica");
                });

            modelBuilder.Entity("Clinica.Domains.Paciente", b =>
                {
                    b.Navigation("Consultas");
                });
#pragma warning restore 612, 618
        }
    }
}
